name: Check Changeset

on:
  pull_request:
    branches:
      - "*"

jobs:
  check-changeset:
    name: Check for Changeset
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Check for changeset if code/package files are changed
        run: |
          set -e
          # Fetch the base branch
          git fetch origin ${{ github.base_ref }}
          # List changed files between base and current commit
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})
          # Patterns that require a changeset
          RELEVANT_PATTERN='^(src/|package.json|constants/|helpers/|types/|public/|vite.config.ts|tsconfig.json)'
          NEED_CHANGESET=false
          while read -r file; do
            if [[ $file =~ $RELEVANT_PATTERN ]]; then
              NEED_CHANGESET=true
              break
            fi
          done <<< "$CHANGED_FILES"
          if [ "$NEED_CHANGESET" = true ]; then
            if ! git ls-files --error-unmatch .changeset/*.md > /dev/null 2>&1; then
              echo "No changeset file found for code/package changes. Please add a changeset (run 'yarn changeset')."
              exit 1
            fi
          else
            echo "No code/package changes detected, changeset not required."
          fi
        shell: bash
