name: PR Checks

on:
  pull_request:
    branches: ["*"]

jobs:
  build-and-lint:
    name: Build, Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Check for changeset
        if: github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]'
        shell: bash
        run: |
          CHANGES=$(git diff --name-status origin/${{ github.base_ref }}...HEAD \
                     | awk '/^A/ && $2 ~ /^\.?changeset\// {print $2}')

          if [[ -z "$CHANGES" ]]; then
            echo "No changeset found, add one to continue"
            exit 1
          else
            echo "✅ Changeset(s) found:"
            echo "$CHANGES"
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Diagnostics
        run: |
          node --version
          npm --version
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Audit
        run: pnpm audit --audit-level=high --prod

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Typecheck
        run: pnpm check-types

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build:all
