name: PR Checks

on:
  pull_request:
    branches: ["*"]

jobs:
  build-and-lint:
    name: Build, Lint & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Check for changeset
        shell: bash
        run: |
          CHANGES=$(git diff --name-status origin/${{ github.base_ref }}...HEAD \
                     | awk '/^A/ && $2 ~ /^\.?changesets\// {print $2}')

          if [[ -z "$CHANGES" ]]; then
            echo "::error ::No changeset found – please add a file under the \"changesets/\" folder."
            exit 1
          else
            echo "✅ Changeset(s) found:"
            echo "$CHANGES"
          fi

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Typecheck
        run: yarn check-types

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format
