name: PR Checks

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-and-lint:
    name: Build, Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for changeset
        run: |
          if ! git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep -E '^.changeset/.*\\.md$' | grep -vqE '^.changeset/(README|config)\\.md$'; then
            echo "No changeset file found. Please add a changeset"
            exit 1
          fi
        shell: bash
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Typecheck
        run: yarn check-types
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
