name: PR Checks

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-and-lint:
    name: Build, Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for changeset
        run: |
          CHANGES=$(git diff --name-status origin/${{ github.base_ref }}...${{ github.head_ref }} \
                     | awk '/^A/ && $2 ~ /^\.?changesets\// {print $2}')

          if [[ -z "$CHANGES" ]]; then
            echo "No changeset found, add a changeset to proceed"
            exit 1
          fi
        shell: bash
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Typecheck
        run: yarn check-types
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
